---
- name: Configure k8s master instance
  hosts: "k8s_nodes"
  gather_facts: False
  become_user: root
  become_method: sudo
  
  tasks:
    - name: Grant ubuntu user right to use docker
      become: True
      raw: usermod -aG docker ubuntu

    - name: Set limits for Elasticsearch
      become: True
      raw: sysctl -w vm.max_map_count=262144

    - name: Create and set permission to folder where Elasticsearch stores data
      become: True
      raw: mkdir -p /var/data/elasticsearch && chown 1000:1000 /var/data/elasticsearch