---
apiVersion: v1
kind: Service
metadata:
  namespace: <%=k8s_namespace%>
  name: <%=service_name%>
  labels: 
    app: <%=microservice_name%>
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: <%=k8s_service_port%>
    protocol: TCP
  selector:
    app: <%=microservice_name%>